title: Raspberry Pi - Light Dependent Resistor
hero_image: images/banner.png
description: Connect LDRs to your Raspberry Pi to automate projects based on ambient light readings.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Light Dependent Resistors
  - title: Using a Light Dependent Resistor
    completion:
    - internal
    completion:
    - engaged
 - title: What can you do now?
    completion:
    - external
